<?php

declare(strict_types=1);

namespace NeuronInteraction\InputHistory;

use NeuronAI\Chat\Messages\ContentBlocks\ReasoningContent;
use NeuronAI\Chat\Messages\ContentBlocks\TextContent;
use NeuronAI\Chat\Messages\UserMessage;
use NeuronInteraction\Message\UserMessageFactory;
use NeuronInteraction\Storage\StorageInterface;
use UnexpectedValueException;

use function array_is_list;
use function array_map;
use function end;
use function is_array;
use function is_string;
use function trim;

/** Submitted inputs shared across Sessions and interaction Adapters. */
final class InputHistory
{
    private const string NAMESPACE = 'input-history';

    private const string KEY = 'entries';

    public function __construct(private readonly StorageInterface $storage) {}

    /**
     * Records the person's original submission, including Command syntax.
     * Adapters must not record prompts generated by Commands here.
     */
    public function append(UserMessage $input): void
    {
        if (!$this->hasUserContent($input)) {
            return;
        }

        // Another Adapter may have submitted input since this instance's
        // previous operation. Append to the current persisted sequence.
        $entries = $this->list();

        if ($entries !== [] && $this->sameInput(end($entries), $input)) {
            return;
        }

        $entries[] = $input;
        $data = array_map(static fn(UserMessage $message): array => $message->jsonSerialize(), $entries);
        $this->storage->write(self::NAMESPACE, self::KEY, $data);
    }

    /**
     * Reads the current shared Storage sequence, oldest first.
     *
     * @return list<UserMessage>
     * @phpstan-impure
     */
    public function list(): array
    {
        $document = $this->storage->read(self::NAMESPACE, self::KEY);
        $entries = $document->data ?? [];

        if (!array_is_list($entries)) {
            throw new UnexpectedValueException(
                'Stored Input history must be a JSON array.',
            );
        }

        $decoded = [];

        foreach ($entries as $entry) {
            if (!is_array($entry)) {
                throw new UnexpectedValueException('Every input history entry must be a user message.');
            }

            $data = [];
            foreach ($entry as $key => $value) {
                if (!is_string($key)) {
                    throw new UnexpectedValueException('An input history message must be an object.');
                }
                $data[$key] = $value;
            }

            $decoded[] = UserMessageFactory::fromArray($data);
        }

        return $decoded;
    }

    private function sameInput(UserMessage $first, UserMessage $second): bool
    {
        $firstData = $first->jsonSerialize();
        $secondData = $second->jsonSerialize();
        // Neuron generates an ID for each instance; it is not authored input.
        unset($firstData['__id'], $secondData['__id']);

        return $firstData === $secondData;
    }

    private function hasUserContent(UserMessage $message): bool
    {
        foreach ($message->getContentBlocks() as $block) {
            if ($block instanceof ReasoningContent) {
                continue;
            }
            if (!$block instanceof TextContent || trim($block->content) !== '') {
                return true;
            }
        }

        return false;
    }
}
