<?php

declare(strict_types=1);

namespace NeuronInteraction\InputHistory;

use NeuronInteraction\Storage\StorageInterface;
use UnexpectedValueException;

/** Submitted inputs shared across Sessions and interaction Adapters. */
final readonly class InputHistory
{
    private const string NAMESPACE = 'input-history';

    private const string KEY = 'entries';

    public function __construct(private StorageInterface $storage) {}

    /**
     * Records the person's original submission, including Command syntax.
     * Adapters must not record prompts generated by Commands here.
     */
    public function record(string $input): void
    {
        if (trim($input) === '') {
            return;
        }

        // Another Adapter may have submitted input since this instance's
        // previous operation. Append to the current persisted sequence.
        $entries = $this->entries();

        if ($entries !== [] && end($entries) === $input) {
            return;
        }

        $entries[] = $input;
        $this->storage->write(self::NAMESPACE, self::KEY, $entries);
    }

    /** @return list<string> Current submitted inputs, oldest first. */
    public function entries(): array
    {
        $document = $this->storage->read(self::NAMESPACE, self::KEY);
        $entries = $document->data ?? [];

        if (!array_is_list($entries)) {
            throw new UnexpectedValueException(
                'Stored Input history must be a JSON array.',
            );
        }

        foreach ($entries as $entry) {
            if (!is_string($entry)) {
                throw new UnexpectedValueException(
                    'Every stored Input history entry must be text.',
                );
            }
        }

        /** @var list<string> $entries */
        return $entries;
    }
}
