<?php

declare(strict_types=1);

namespace NeuronInteraction\InputHistory;

use NeuronAI\Chat\Messages\ContentBlocks\ReasoningContent;
use NeuronAI\Chat\Messages\ContentBlocks\TextContent;
use NeuronAI\Chat\Messages\UserMessage;
use NeuronInteraction\Storage\StorageInterface;
use UnexpectedValueException;

/** Submitted inputs shared across Sessions and interaction Adapters. */
final class InputHistory
{
    private const string NAMESPACE = 'input-history';

    private const string KEY = 'entries';

    private ?int $position = null;

    private ?UserMessage $draft = null;

    public function __construct(private readonly StorageInterface $storage)
    {
    }

    /**
     * Records the person's original submission, including Command syntax.
     * Adapters must not record prompts generated by Commands here.
     */
    public function record(UserMessage $input): void
    {
        if (!$this->hasUserContent($input)) {
            return;
        }

        // Another Adapter may have submitted input since this instance's
        // previous operation. Append to the current persisted sequence.
        $entries = $this->entries();

        if ($entries !== [] && $this->sameInput(end($entries), $input)) {
            return;
        }

        $entries[] = $input;
        $this->storage->write(self::NAMESPACE, self::KEY, array_map(static fn (UserMessage $message): array => $message->jsonSerialize(), $entries));
    }

    /**
     * Moves toward older inputs, entering navigation at the newest one.
     *
     * @phpstan-impure
     */
    public function older(UserMessage $draft = new UserMessage('')): ?UserMessage
    {
        $entries = $this->entries();

        if ($entries === []) {
            return null;
        }

        if ($this->position === null) {
            $this->draft = $draft;
            $this->position = array_key_last($entries);
        } else {
            $this->position = max(0, $this->position - 1);
        }

        return $entries[$this->position];
    }

    /**
     * Moves toward newer inputs, restoring the draft past the end.
     *
     * @phpstan-impure
     */
    public function newer(): ?UserMessage
    {
        if ($this->position === null) {
            return null;
        }

        $entries = $this->entries();

        if ($this->position === array_key_last($entries)) {
            $draft = $this->draft;
            $this->leave();

            return $draft;
        }

        ++$this->position;

        return $entries[$this->position];
    }

    public function isNavigating(): bool
    {
        return $this->position !== null;
    }

    /** The composer draft has become independent from its stored source. */
    public function leave(): void
    {
        $this->position = null;
        $this->draft = null;
    }

    /**
     * Reads the current shared Storage sequence, oldest first.
     *
     * @return list<UserMessage>
     * @phpstan-impure
     */
    public function entries(): array
    {
        $document = $this->storage->read(self::NAMESPACE, self::KEY);
        $entries = $document->data ?? [];

        if (!array_is_list($entries)) {
            throw new UnexpectedValueException(
                'Stored Input history must be a JSON array.',
            );
        }

        $decoded = [];
        $deserializer = new UserMessageDeserializer();

        foreach ($entries as $entry) {
            if (!is_array($entry)) {
                throw new UnexpectedValueException('Every input history entry must be a user message.');
            }

            $data = [];
            foreach ($entry as $key => $value) {
                if (!is_string($key)) {
                    throw new UnexpectedValueException('An input history message must be an object.');
                }
                $data[$key] = $value;
            }

            $decoded[] = $deserializer->deserialize($data);
        }

        return $decoded;
    }

    private function sameInput(UserMessage $first, UserMessage $second): bool
    {
        $firstData = $first->jsonSerialize();
        $secondData = $second->jsonSerialize();
        // Neuron generates an ID for each instance; it is not authored input.
        unset($firstData['__id'], $secondData['__id']);

        return $firstData === $secondData;
    }

    private function hasUserContent(UserMessage $message): bool
    {
        foreach ($message->getContentBlocks() as $block) {
            if ($block instanceof ReasoningContent) {
                continue;
            }
            if (!$block instanceof TextContent || trim($block->content) !== '') {
                return true;
            }
        }

        return false;
    }
}
